- backend/package-lock.json
- frontend/package-lock.json
- frontend/src/router/index.js
- frontend/src/views/Question.vue
- frontend/src/views/Questions.vue
- package-lock.json
- 체리카드 뉴스에서 각 분야별로 분리되었던 vue 파일을 삭제 (News.vue 사용)
- QuestionList.vue 코드를 Questions.vue로 이동.
> GNB 페이지 수정

- backend/package-lock.json
- backend/routes/index.js
- backend/routes/question.route.js
- frontend/package-lock.json
- frontend/src/components/Header/HeaderDropdown.vue
- frontend/src/views/NewQuestion.vue
- frontend/src/views/Question.vue
- frontend/src/views/Questions.vue
- package-lock.json
주요 변경 사항
* api/question -> api/questions
* HeaderDropdown.vue 에러 수정
* package-lock 수정 
(이 파일은 수정이 안되어야 하는게 맞는 것 같은데, 신규 노드 패키지 설치를 하고 나니 변경되어 있었습니다. 이상있을 경우 알려주세요)
> 버그 수정 및 리팩토링

- frontend/package.json
- frontend/src/views/NewQuestion.vue
- frontend/src/views/Question.vue
- 분야 선택에 따른 입력 필드 변경
- 제목 및 내용 입력
- 태그 입력
> 질문 작성 #13 #40

- backend/app.js
- backend/config/config.js
- backend/controllers/auth.controller.js
- backend/routes/auth.route.js
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/views/Login.vue
- jwt 유효시간 1일로 설정.
- 질문 등록, Cherry Transfer, 프로필 화면 접근 시 로그인 여부 체크하도록 설정.
- 로그인 필수 페이지의 path를 저장하고, 로그인 후에 이동할 수 있도록 구현.
> #42 회원 로그인 구현 완료

- backend/app.js
- backend/config/config.js
- backend/controllers/auth.controller.js
- backend/controllers/user.controller.js
- backend/routes/index.js
- backend/routes/user.route.js
- frontend/src/main.js
- frontend/src/views/Login.vue
- frontend/src/views/Profile.vue
* backend API를 사용할 수 있도록, 몇 가지 빠져있던 기본 세팅을 적용
* backend API 호출시 'me'라는 키워드를 사용하지 않기 위해서, 로그인시 세션에 _id값을 저장하도록 작업
> 프로필 - 수치(좌측) 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/main.js
- frontend/src/store.js
- frontend/src/views/Profile.vue
@clghks 
form 작성하다보면 많은 옵션 값들이 있는데요. 
그 옵션 값들을 한곳에서 관리하기 위해 store 기능을 추가하였습니다.
> vuex store 사용

- backend/controllers/user.controller.js
- backend/routes/user.route.js
- frontend/src/router/index.js
- frontend/src/store.js
- frontend/src/views/Profile.vue
* 프로필 업데이트 로직 구현
* 프로필 정보 옵션 추가
* 최초 업데이트시 보상
> add : 프로필 업데이트 로직

- backend/controllers/auth.controller.js
- backend/controllers/contract.controller.js
- backend/controllers/question.controller.js
- backend/routes/contract.route.js
- backend/routes/question.route.js
- frontend/src/assets/scss/_custom.scss
- frontend/src/views/CherryTransfer.vue
- frontend/src/views/NewQuestion.vue
- frontend/src/views/NewsDetail.vue
- frontend/src/views/Questions.vue
- 질문 작성 (체리 -4 소진) #39
- 질문 작성 #13
> 질문 작성 (체리 -4 소진) #39

- backend/controllers/contract.controller.js
- backend/controllers/user.controller.js
- backend/routes/user.route.js
토큰 전송 시 응답 시간이 오래 걸려 UX측면에서 알림 기능 필요
> 최초 profile 업데이트 시 체리 +10

- frontend/package-lock.json
- frontend/src/assets/scss/_custom.scss
- frontend/src/main.js
- frontend/src/views/CherryTransfer.vue
- frontend/src/views/Profile.vue
- frontend/src/views/base/Table.vue
스프린트 1차 종료 시 나온 변경 기능 및 미구현 부분 적용
> 기타 버그 및 변경 사항 적용

- backend/controllers/answer.controller.js
- backend/controllers/contract.controller.js
- backend/controllers/like.controller.js
- backend/models/answer.model.js
- backend/models/like.model.js
- backend/routes/answer.route.js
- backend/routes/like.route.js
- frontend/src/views/Question.vue
answer & like 조회 API 기능 추가
@kioku714 
Like 등록시, questionOrAnswerModel을 등록하지 않는 부분을 추가하면서 기존 코드 변경 작업이 다소 있었습니다.
리뷰 부탁드리고, 문제 있는 부분 피드백 주세요~
> answer & like 조회 API 추가 및 등록 API 수정

- backend/controllers/like.controller.js
- frontend/src/views/Question.vue
06ff46c302f1fe41bb87aecd8134851ac6b50459 로 인한 Side effect 수정
- 질문에 좋아요를 클릭 시 transaction  전송되지 않는 에러 수정.
- 답변 생성 후 화면이 갱신되지 않는 에러 수정.
- 답변에 좋아요를 클릭한 후 화면이 갱신되지 않는 에러 수정.
> Side effect 수정

- frontend/src/views/NewQuestion.vue
- frontend/src/views/Profile.vue
- frontend/src/views/Question.vue
프로필 - 알림 #27 
* 나이 계산 로직, $moment로 코드 간결화
> 프로필 - 알림 구현 및 리팩토링

- backend/app.js
- backend/config/param-validation.js
- backend/controllers/contract.controller.js
- backend/controllers/event.controller.js
- backend/controllers/like.controller.js
- backend/models/event.model.js
- backend/routes/answer.route.js
- backend/routes/contract.route.js
- backend/routes/index.js
- backend/routes/like.route.js
- backend/routes/question.route.js
- backend/routes/user.route.js
- frontend/src/views/Profile.vue
event 적용 완료 
전체 인터페이스 통일을 위해 기존 코드 리팩토링
> event 전체 적용 및 리팩토링

- frontend/package.json
- frontend/src/assets/scss/_custom.scss
- frontend/src/main.js
- frontend/src/views/NewQuestion.vue
- frontend/src/views/Question.vue
- 답변 등록, 질문/답변 좋아요에 loading indicator 추가.
- 질문 상세에서 답변 리스트 영역의 background color 변경.
> 액션 로딩 안내 #80

- backend/config/param-validation.js
- frontend/src/assets/scss/_custom.scss
- frontend/src/views/NewQuestion.vue
- frontend/src/views/News.vue
- frontend/src/views/NewsDetail.vue
- frontend/src/views/Profile.vue
- frontend/src/views/Question.vue
- 질문 등록, 최초 프로필 수정에 로딩 indicator 추가.
- createAnswer validation 추가.
> 로딩 indicator 추가 및 전체적인 UI 수정

- frontend/src/store.js
- frontend/src/views/NewQuestion.vue
- frontend/src/views/Profile.vue
- 질문, 프로필 카테고리 select box 선택 옵션 #127
> 질문, 프로필 카테고리 select box 선택 옵션 #127

- frontend/src/components/Header/HeaderDropdown.vue
- frontend/src/views/CherryTransfer.vue
- frontend/src/views/Profile.vue
- frontend/src/views/Question.vue
- (Minor) 프로필 동그라미 색상 랜덤 #148
- bittermoon, chris, miin_dong, hyungn11, autumn091 계정 추가
- (Major) 모바일 사이즈에서 프로필 아이콘 누르면 뜨는 메뉴 #146
- HeaderDropdown 메뉴의 Cherry Transfer에 userId 파라미터 추가
> #146 #148 이슈 처리

- frontend/src/components/Sidebar/SidebarNavDropdown.vue
> (Normal) GNB 서브메뉴 클릭 시 서브메뉴 닫힘 현상

- backend/controllers/answer.controller.js
- backend/models/answer.model.js
- frontend/src/views/Profile.vue
- frontend/src/views/Question.vue
> (Normal) 답변 정렬 기준 변경

- frontend/src/assets/scss/_custom.scss
- frontend/src/views/Question.vue
참고: https://getbootstrap.com/docs/4.1/content/images/#responsive-images
> 답변 영역 이미지 리사이징 추가
